
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/bbechtle/Projects/clion/clion-2024.2.1/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.9.12-3-MANJARO - x86_64
...
